version: '3.3'

servicesm: 
  postgressql:
    container_name: postgressql-servidor
    image: postgres:latest
    
    networks:
      - redinterna
    
    ports:
      - "5432:5432"
   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bdprueba
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./_data:/var/lib/postgresql
    
    restart: always

networks:
  redinterna:
     